version: "3"
services:
  item-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=item-db
    depends_on:
      - item-db

  item-db:
    image: mongo:3
    ports:
      - "27017:27017"
    volumes:
      - app-db:/data/db

volumes:
  app-db:
